# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGoogleSignin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestGoogleSignin
  pod 'GoogleSignIn'

  target 'TestGoogleSigninTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestGoogleSignin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestGoogleSignin-tvOS

  target 'TestGoogleSignin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
